DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS
(
    USER_ID     NUMERIC NOT NULL AUTO_INCREMENT,
    USERNAME    VARCHAR(255) NULL,
    PASSWORD    VARCHAR(255) NULL,
    FIRST_NAME  VARCHAR(255) NULL,
    LAST_NAME   VARCHAR(255) NULL,
    LOCALE      VARCHAR(255) NULL,
    USER_STATUS VARCHAR(255) NULL,
    CONSTRAINT PK_USERS PRIMARY KEY (USER_ID)
);

ALTER TABLE USERS
    ADD CONSTRAINT UC_USERS_USERNAME UNIQUE (USERNAME);

DROP TABLE IF EXISTS BILL_TAX_TYPES;

CREATE TABLE BILL_TAX_TYPES
(
    GKEY         NUMERIC NOT NULL AUTO_INCREMENT,
    ID                  VARCHAR(255) NULL,
    `DESCRIPTION`       VARCHAR(255) NULL,
    GL_CODE             VARCHAR(255) NULL,
    COMPLEX_GENERIC_KEY NUMERIC     NULL,
    CREATED             DATETIME     NULL,
    CREATOR             VARCHAR(255) NULL,
    CHANGED             DATETIME     NULL,
    CHANGER             VARCHAR(255) NULL,
    LIFE_CYCLE_STATE    VARCHAR(255) NULL,
    CONSTRAINT PK_BILLTAXTYPES PRIMARY KEY (GKEY)
);